name: RAIN

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install package
      run: |
        sudo apt-get -y install ffmpeg git nodejs imagemagick wget
        
    - name: Download File Bot
      run: |
        git clone https://github.com/AyGemuy/RAIN
        
    - name: Run File Bot
      run: |
        cd RAIN && npm install && node . --server
